# Generated by Django 5.0.1 on 2024-01-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_habit_created_at'),
        ('main_app', '0004_habit_status'),
    ]

    operations = [
    ]
