# Generated by Django 5.0.1 on 2024-01-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_habit_frequency_habit_unit_alter_habit_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
