# Generated by Django 5.0.1 on 2024-01-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_habit_category_alter_habit_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='unit',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
