# Generated by Django 5.0.1 on 2024-01-23 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_journal_options_journal_date_journal_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='mood',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
