# Generated by Django 5.0.1 on 2024-01-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_habit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='streak',
            new_name='goal',
        ),
    ]
