# Generated by Django 5.0.1 on 2024-01-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_streak_habit_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
