# Generated by Django 5.0.1 on 2024-01-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_merge_0004_habit_created_at_0004_habit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Fitness', 'Fitness'), ('Personal Development', 'Personal Development'), ('Relationships', 'Relationships')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
