# Generated by Django 5.0.1 on 2024-01-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_habit_category'),
        ('main_app', '0009_remove_event_description'),
    ]

    operations = [
    ]
