# Generated by Django 5.0.1 on 2024-01-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='make_or_break',
            field=models.CharField(choices=[('Make', 'Make'), ('Break', 'Break')], max_length=5),
        ),
    ]
