# Generated by Django 5.0.1 on 2024-01-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_habit_make_or_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='frequency',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='unit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='habit',
            name='make_or_break',
            field=models.CharField(max_length=100),
        ),
    ]
