# Generated by Django 5.0.1 on 2024-01-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_habit_frequency_alter_habit_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='habit',
            field=models.ManyToManyField(to='main_app.habit'),
        ),
    ]
