# Generated by Django 5.0.1 on 2024-01-23 16:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_journal_habit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='journal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Journal Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='journal',
            name='habit',
        ),
        migrations.AddField(
            model_name='journal',
            name='habit',
            field=models.ForeignKey(default=62, on_delete=django.db.models.deletion.CASCADE, to='main_app.habit'),
            preserve_default=False,
        ),
    ]
